version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
